### ISSUE TITLE
Can't find the app on playstore!

### ISSUE THREAD

**Issue by d1ndonlymdhe** [frank240889/MusicalLibraryOrganizer#4]
Couldn't find the app with the given link.
Where can I find an apk?

**Comment by frank240889** [comment]
The ACR SDK used in the app (part of the core functionality) has no longer available anymore since 1.5 -2 years, for that reason I had to removed the app from PlayStore, sorry, currently I working on to refactor to Kotlin the entire app and searching another ACR public and free API suitable to be used in the app.
